### ISSUE TITLE
Battle Garegga - lines missing on left

### ISSUE THREAD

**Issue by zakk4223** [psomashekar/pr4m0d-MISTer-bin#20]
There seems to be a few lines getting cut off on the left side of the garegga screen.

Core:
![Screenshot 2022-07-22 18-29-38](https://user-images.githubusercontent.com/22642/180578088-e5123148-e070-4e53-8720-68c912fd8188.png)

PCB:
![IMG_1993](https://user-images.githubusercontent.com/22642/180578325-d49bd4a3-4874-4148-aba3-0fe4ea865ffe.jpg)

The 'P' on the core seems a bit too thin. I also have custom code that writes text to the left most lines of the screen and those are also slightly cut off.

**Comment by psomashekar** [comment]
Thanks Zakk, I will take a look.

**Comment by psomashekar** [comment]
@zakk4223 I fixed this,  but @atrac17 is working on SDRAM compatibility and fixing the pll/ clocks so the fix wont be available until after that's in there. Long story short, the issue was with the renderer. I was only drawing lines where its in the hblank period and not in the vblank period. But, line 0 is a special case. It really has to be drawn at the end of the vblank period while it is still in hblank (line 263). So, adding this special case fixed it, and your text is visible completely.
